spring.application.name=reservation

spring.datasource.url=jdbc:mysql://localhost:3306/train_db
spring.datasource.username=root
spring.datasource.password=426200

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
